66 create a may produce false information message at the bottom of chats
kylexrich/coursegpt pull request #87
Opened 2023-06-23 14:48 UTC by ritikk7

warning message added

2023-06-23 15:00 UTC, kylexrich requested changes
Looks great! Do you think that we might be producing false information about people, places, and facts though? Or are there other categories that might be more applicable to CourseGPT?

2023-06-23 15:08 UTC, ritikk7 commented
> Looks great! Do you think that we might be producing false information about people, places, and facts though? Or are there other categories that might be more applicable to CourseGPT?

I consulted ChatGPT on this lol. People, Places, and Facts sum up most of what an AI could produce wrong in a single short line. In our case People could mean outdated instructor info, places could mean outdated class/exam locations, and well facts could mean any course content so I didn't bother changing that.

2023-06-23 15:48 UTC, kylexrich requested changes

2023-06-23 15:48 UTC, kylexrich commented on client/src/components/organisms/RightSection/RightSection.js
> +    <Message value={"CourseGPT may produce inaccurate information about people, places, or facts. [CourseGPT June 30 Version]"}/>
What about: "CourseGPT may produce inaccurate information about instructors or course information. [CourseGPT 2023 Version]"

2023-06-23 20:56 UTC, huangcar1 commented
I think that both make sense + it depends on if we want to go for something more general/specific! I think I prefer the specific one, but I don't really have a strong preference. The date should definitely be the year, though, otherwise we'll have to change it constantly or it'll look outdated.

2023-06-23 21:25 UTC, ajo01 commented
I'm fine with either. The specific version is exactly what ChatGPT has right now. Also agree with only putting up the year.

2023-06-24 03:51 UTC, duffydu commented
I would also prefer the more specific version. And +1 for the year

2023-06-24 04:06 UTC, ajo01 approved these changes

2023-06-24 04:09 UTC, duffydu approved these changes

2023-06-24 13:14 UTC, huangcar1 approved these changes

2023-06-24 13:25 UTC, kylexrich approved these changes

2023-06-24 15:57 UTC, merged